export const NAVIGATION_FORWARD = 'NAVIGATION_FORWARD';
export const NAVIGATION_BACK = 'NAVIGATION_BACK';
export const ADD_RECIPE = 'ADD_RECIPE';
//export const GET_COUPONS = 'GET_COUPONS';
export const SET_FOUND_COUPONS = 'SET_FOUND_COUPONS';
export const SET_SEARCHED_COUPONS = 'SET_SEARCHED_COUPONS';
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const REFRESH_STATUS = 'REFRESH_STATUS';
export const SET_REFRESH_STATUS = 'SET_REFRESH_STATUS';
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const SET_FOUND_SLIDES = 'SET_FOUND_SLIDES';
export const SET_FOUND_CATEGORIES = 'SET_FOUND_CATEGORIES';

//Coupons
export const SET_LATEST_COUPONS = 'SET_LATEST_COUPONS';
export const SET_TOP_COUPONS = 'SET_TOP_COUPONS';
export const SET_EXPIRING_COUPONS = 'SET_EXPIRING_COUPONS';
export const SET_FEATURED_COUPONS = 'SET_FEATURED_COUPONS';
export const SET_POPULAR_COUPONS = 'SET_POPULAR_COUPONS';

//Merchants
export const SET_SEARCHED_MERCHANTS = 'SET_SEARCHED_MERCHANTS';
export const SET_MERCHANT_DETAIL = 'SET_MERCHANT_DETAIL';
export const GET_MERCHANT_DETAIL = 'GET_MERCHANT_DETAIL';
export const SEARCH_MERCHANT = 'SEARCH_MERCHANT';

//Category
export const LIST_CATEGORIES = 'LIST_CATEGORIES';
export const GET_CATEGORY_OFFERS = 'GET_CATEGORY_OFFERS';
export const SET_CATEGORY_OFFERS = 'SET_CATEGORY_OFFERS';

//Errors
export const API_FETCH_FAILED = 'API_FETCH_FAILED';


export const GET_SLIDERS = 'GET_SLIDERS';
export const GET_ACCESS_TOKEN = 'GET_ACCESS_TOKEN';
export const GET_COUPONS = 'GET_COUPONS';
export const SEARCH_COUPONS = 'SEARCH_COUPONS';